name: 🐛 Bug Report
description: File a bug report
title: "🐛 "
labels: ["bug"]
assignees:
  - bradystroud
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: ""
    validations:
      required: true

